# Generated by Django 2.2.4 on 2021-06-20 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20210617_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='fellows', to=settings.AUTH_USER_MODEL),
        ),
    ]
