# Generated by Django 2.2.4 on 2021-06-23 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='user1'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='user2'),
        ),
    ]
