# Generated by Django 2.2.4 on 2021-06-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210623_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='chat_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
