# Generated by Django 2.2.4 on 2021-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210625_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatters',
            name='msg_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
