# Generated by Django 2.2.4 on 2021-06-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_chatters_msg_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_table',
            name='login',
            field=models.BooleanField(default=True),
        ),
    ]
