# Generated by Django 2.2.4 on 2021-06-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_register_table_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Institute',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
