# Generated by Django 2.2.4 on 2021-06-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='mid1',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='mid2',
            field=models.TextField(null=True, verbose_name='body'),
        ),
    ]
