# Generated by Django 2.2.4 on 2021-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210627_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='mid1',
            field=models.TextField(null=True, verbose_name='mid1'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='mid2',
            field=models.TextField(null=True, verbose_name='mid2'),
        ),
    ]
