# Generated by Django 2.2.4 on 2021-06-27 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_auto_20210627_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='mid1',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='mid2',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='midUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid_user', to=settings.AUTH_USER_MODEL, verbose_name='mid'),
        ),
    ]
