# Generated by Django 2.2.4 on 2021-06-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20210627_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='midUser',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
