# Generated by Django 2.2.4 on 2021-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210627_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='midUser',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='msg1',
            field=models.TextField(blank=True, null=True, verbose_name='msg1'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='msg2',
            field=models.TextField(blank=True, null=True, verbose_name='msg2'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='body'),
        ),
    ]
