# Generated by Django 2.2.4 on 2021-06-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20210627_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_table',
            name='login',
            field=models.IntegerField(default=1),
        ),
    ]
