# Generated by Django 2.2.4 on 2021-06-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210629_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatters',
            name='msg_count',
            field=models.FloatField(default=0),
        ),
    ]
